Lesson8
Shorokhov-A/repo-geekshop pull request #9
Opened 2021-11-03 19:56 UTC by Shorokhov-A

Постарался перевести на CBV максимум контроллеров проекта.
Особенно интересует Ваше мнение по поводу контроллера ProductsListView приложения products.
В процессе создания этого контроллера выяснилось, что пагинация работает корректно только при условии отображения товаров по всем категориям. При отображении товаров только конкретных категорий пагинация, написанная на вебинаре, не работает.
Также интересно Ваше мнение насёт контроллера ProfileUpdateView приложения users.
Да, в общем, по всей работе хотелось бы получить содержательную критику. )

2021-11-07 16:54 UTC, Vokler requested changes
Вот тут проект, который полностью реализован на CBV (кроме приложения baskets - так как там нет необходимости в этом), можете ознакомиться, если интересно и дополнить свой проект :)

https://github.com/Vokler/geekshop-569-728

Там как раз найдете ответы на свои вопросы)

2021-11-07 16:54 UTC, Vokler commented on products/views.py
> +        context['title'] = 'GeekShop - Каталог'
Здесь можно использовать метод `update()` для контекста, чтобы не создавать дублирующиеся строчки:
```
context.updtae({
    'title': 'GeekShop - Каталог',
    'header': 'GeekShop',
    'categories': 'ProductCategory.objects.all()'
})
```

2021-11-08 09:33 UTC, Shorokhov-A commented on products/views.py
> +        context['title'] = 'GeekShop - Каталог'
Точно.

2021-11-08 09:42 UTC, Shorokhov-A commented
И переопределенные методы form_valid() в приложении users лучше бы переписать следующим образом:
def form_valid(self, form):
    super().form_valid(form)
    messages.success(self.request, 'Изменения сохранены!')
    return HttpResponseRedirect(self.get_success_url())
В моих методах получается, что сообщения отправляются раньше, чем изменения действительно будут сохранены. )

2021-11-08 09:50 UTC, Shorokhov-A commented on users/views.py
> +
Наверное, лучше так:

def form_valid(self, form):
    super().form_valid(form)
    messages.success(self.request, 'Вы успешно зарегистрировались!')
    return HttpResponseRedirect(self.get_success_url())

2021-11-08 09:59 UTC, Shorokhov-A commented on users/views.py
>                  auth.login(request, user)
Вот здесь, наверное переопределение метода ```post()``` вообще лучше убрать и перенести авторизацию в метод ```form_valid()```.

2021-11-08 10:20 UTC, Shorokhov-A commented on users/views.py
> +        return super().form_valid(form)
А здесь так:
```
def form_valid(self, form):
    super().form_valid(form)
    messages.success(self.request, 'Изменения сохранены!')
    return HttpResponseRedirect(self.get_success_url())
```

2021-11-08 15:54 UTC, Shorokhov-A commented
Получается, что и CommonContextMixin не особо нужен, если у вьюх есть свойство extra_context... )
Кошмар. Так и крыша может поехать... Это всё никуда не годится. Всё нужно переписывать... )))

2021-11-11 12:11 UTC, merged